name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: 'npm install'

      - name: Run lint
        run: 'npm run lint'

      - name: Run build
        run: 'npm run build'

      - name: Publish to npmjs
        run: 'npm run release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages
        run: 'npm run release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
